config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :products
  resources :product_comments, only: [:create, :edit, :destroy]
  resources :carts, only: [:show, :index, :create]
  resources :cart_products, only: [:create, :update, :destroy]
  resources :talks, only: [:create, :destroy]
  resources :users, only: [:show, :edit, :destroy, :update]
  resources :buys, only: [:show]
  resources :buy_products, only: [:update, :destroy]
  resources :mails, only: [:create, :new]

  resources :admins, only: [:index, :show]
  get 'search' => 'searches#search', as: "search"
  get "/homes/about" => "homes#about"
  get '/delivery' => 'users#delivery'
  post '/delivery/:id' => 'users#delivery_create'
  root to: 'products#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
      # if user.admin?
      #   can :manage, :all
      # else
      #   can :read, :all
      # end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    if user && user.admin?
        can :access, :rails_admin
        can :manage, :all
    end
  end
end

app/models/buy.rb
class Buy < ApplicationRecord
	belongs_to :user
	has_many :buy_products, :dependent => :destroy
	belongs_to :delivery, inverse_of: :buys, optional: true
	enum payment: {クレジットカード: 0, 代金引換: 1, コンビニ払い: 2, 銀行振込: 3}
end

app/models/buy_product.rb
class BuyProduct < ApplicationRecord
	belongs_to :product
	belongs_to :buy
	enum delivery_status: {配送準備中: 0, 配送中: 1, 出荷済み: 2}
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_many :cart_products, :dependent => :destroy
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
	belongs_to :product
	belongs_to :cart

	validates :count,{presence: true}

end

app/models/delivery.rb
class Delivery < ApplicationRecord
	belongs_to :user
	has_many :buys, inverse_of: :delivery
	accepts_nested_attributes_for :buys
end

app/models/disc.rb
class Disc < ApplicationRecord
	belongs_to :product
	has_many :songs, inverse_of: :disc, :dependent => :destroy
	accepts_nested_attributes_for :songs, allow_destroy: true
end

app/models/mail.rb
class Mail < ApplicationRecord
	validates :name, :email, :subject, :content, presence: true
	belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord

	 enum genre: { 'J-POP': 0, 洋楽: 1, 'K-POP': 2, アニメ: 3, 'HIP-HOP': 4, レゲエ: 5,
	 	ロック: 6, 演歌: 7, エレクトロニック: 8, クラシック: 9, メタル: 10}
	 # enum genre: {aaa: 0, abb: 1, ccc: 3}
	 enum status: {新品: 0, 未使用に近い: 1, 目立った傷汚れなし: 2, 傷汚れあり: 3, 状態が悪い: 4}
	 enum delivery_status: {配送準備中: 0, 配送中: 1, 出荷済み: 2}


	 validates :artist, presence:true

	 validates :album, {presence:true}
	 validates :label, {presence:true}
	 validates :genre, {presence:true}
	 validates :status, {presence:true}
	 validates :introduction, {presence:true}
	 # validates :count, {presence:true}
	 validates :count,  presence: true
	 # validates :price, {presence:true}
	 validates :price,  presence: true

	belongs_to :user
	has_many :product_comments, :dependent => :destroy

 	has_many :discs, inverse_of: :product, :dependent => :destroy
	accepts_nested_attributes_for :discs, allow_destroy: true

	has_many :cart_products, :dependent => :destroy
	has_many :buy_products, :dependent => :destroy
	attachment :image
end

app/models/product_comment.rb
class ProductComment < ApplicationRecord
	belongs_to :user
	belongs_to :product

	validates :content, {presence:true}
end

app/models/room.rb
class Room < ApplicationRecord
	belongs_to :user
	has_many :talks, :dependent => :destroy
end

app/models/song.rb
class Song < ApplicationRecord
	belongs_to :disc
end

app/models/talk.rb
class Talk < ApplicationRecord
	belongs_to :room
	belongs_to :user

	validates :content,{presence: true}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum deleted_at: {登録中: 0, 退会済み: 1}

  def active_for_authentication?
    super && self.deleted_at == "登録中"
  end

  def inactive_message
    self.deleted_at == "登録中" ? super: :退会済みのユーザーです
  end

   has_many :mails
   has_many :products
   has_one :room
   has_many :talks
   has_many :product_comments
   has_one :cart
   has_many :deliveries
   has_many :buys

   attachment :image
   validates :name,:name_kana, :email, :password,:password_confirmation,:postal,:state,:street,:adress,:tel,{presence: true}


   validates :tel, length:{minimum:10}
   validates :tel, length:{maximum:11}
   validates :postal, length:{is:7}
   validates :password,length:{minimum:6}
   

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user! ,only: [:show,:edit]
  before_action :room_user, only:[:show]

  def show #---マイページ画面---#
  	@user = User.find(params[:id])
    @talk = Talk.new
    @room = Room.find_by(user_id: params[:id])
    @talk1 = Talk.where(room_id: @room.id)
    # @p = Room.find_by(id: params[:id])  #---インスタンス変数@pにRoomモデルのuser_idをユーザのURLから探してきている---#
    # @talk1 = Talk.where(room_id: @p.id)
    @buys = Buy.where(user_id: current_user.id)
  end

  def edit
  	@user = User.find_by(id: current_user.id) #---マイページ編集画面---#
  end

  def update #---マイページ編集画面の情報アップデート---#
  	@user = User.find(params[:id])
  	if @user.update(user_params)
         sign_in(@user, bypass: true) #---deviseではパスワードを変更するとログアウトする仕組みの為記入をしました---#
  		redirect_to user_path(@user), notce: "保存しました"
  	else
  		render :edit
  	end
  end

  def destroy
    @user = User.find(params[:id])
    @user.update_attribute(:deleted_at, 1)
    @user.products.destroy
    @user.talks.destroy
    @user.product_comments.destroy
    redirect_to new_user_registration_path
  end

  def delivery
    @buys = Buy.where(user_id: current_user.id)
  end

  def delivery_create
    @buy = Buy.where(user_id: current_user.id)
    @buy.each do |buy|
      buy.buy_products.each do |buy_product|
        name = buy_product.id.to_s + "_delivery_status"
        buy_product.delivery_status = params[name]
        buy_product.save
      end
    end
    redirect_to user_path(current_user.id)
  end

  private
  def user_params
  	params.require(:user).permit(:name, :name_kana, :email, :password,:password_confirmation,:postal,:state,:street,:adress,:tel,:profile,:image)
  end
  def room_user
      if Room.where(user_id: params[:id]).exists?
      else
        @room = Room.new(user_id: params[:id])
        @room.save
      end
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/buys_helper.rb
module BuysHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/mails_helper.rb
module MailsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/delivery.html.erb
<h1>配送状況</h1>

<div class="users_delivery_status_box">
	<%= form_tag("/delivery/#{current_user.id}", method: :post) do %>
		<table>
			<tr>
				<th>アーティスト名</th>
				<th>アルバム名</th>
				<th>レーベル名</th>
				<th>値段</th>
				<th>注文数</th>
				<th>配送状況</th>
			</tr>
				<% @buys.each do |buy| %>
					<% buy.buy_products.each do |buy_product| %>
						<tr>
							<!-- アーティスト名 -->
							<td><%= buy_product.product.artist %></td>
							<!-- アルバム名 -->
							<td><%= buy_product.product.album %></td>
							<!-- レーベル -->
							<td><%= buy_product.product.album %></td>
							<!-- 値段 -->
							<td><%= buy_product.price %></td>
							<!-- 注文数 -->
							<td><%= buy_product.count %></td>
							<!-- 配送状況 -->
							<% buy_product_name = buy_product.id.to_s + "_delivery_status" %>
							<td><%= select_tag buy_product_name, options_for_select([["配送準備中", "配送準備中"],["配送中", "配送中"],["出荷済み", "出荷済み"]], selected: buy_product.delivery_status) %></td>
						</tr>
					<% end %>
				<% end %>

		</table>
	<div>
		<%= submit_tag '配送状況を保存' %>
	</div>
	<% end %>
</div>

app/views/users/edit.html.erb
<div class="users_edit_mypage">
	<%= form_for(@user) do |f| %>
	<div class="users_edit_left">
		<div class="users_edit_errors">
		<% if @user.errors.any? %>
		<h3><%= @user.errors.count %>件のエラーがあります</h3>
		<ul>
			<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
		<% end %>
	</div>
		<h1>マイページ編集画面</h1>
		<div class="users_edit_accountimage">
			<div>
				<h4>プロフィール画像</h4>
				<%= f.attachment_field :image %>
			</div>
			<div>
				<h4>プロフィールコメント</h4>
				<%= f.text_area :profile, :size => "80x20",placeholder:"200文字以内" %>
			</div>


		</div>
	</div>
	<div class="users_edit_right">
		<div class="users_edit_account">
			<div>
				<h4>氏名(漢字)</h4>
				<%= f.text_field :name, placeholder:"漢字",:size => "30" ,class: "users_edit_account_edit"%>
			</div>
			<div>
				<h4>名前(カナ)</h4>
				<%= f.text_field :name_kana, placeholder:"カタカナ",class: "users_edit_account_edit"%>
			</div>
			<div>
				<h4>メールアドレス</h4>
				<%= f.email_field :email ,placeholder:"メールアドレス",class: "users_edit_account_edit"%>
			</div>
			<div>
				<h4>パスワード</h4>
				<%= f.password_field :password ,placeholder:"パスワード(6文字以上)",class: "users_edit_account_edit"%>
			</div>
			<div>
				<h4>パスワード確認</h4>
				<%= f.password_field :password_confirmation ,placeholder:"パスワード確認(6文字以上)",class: "users_edit_account_edit"%>
			</div>
			<div>
				<h4>郵便番号</h4>
				<%= f.text_field :postal ,placeholder:"郵便番号",class: "users_edit_account_edit"%>
			</div>
			<div>
				<h4>都道府県</h4>
				<%= f.text_field :state ,placeholder:"都道府県",class: "users_edit_account_edit"%>
			</div>
			<div>
				<h4>市区町村</h4>
				<%= f.text_field :street ,placeholder:"市区町村",class: "users_edit_account_edit"%>
			</div>
			<div>
				<h4>番地以降</h4>
				<%= f.text_field :adress ,placeholder:"番地以降",class: "users_edit_account_edit"%>
			</div>
			<div>
				<h4>電話番号</h4>
				<%= f.text_field :tel ,placeholder:"電話番号",class: "users_edit_account_edit"%>
			</div>
			<div>
				<%= f.submit '保存', class: "users_edit_account_edit" %>
			</div>
		<% end %>
			<%=link_to"戻る", user_path(@user) %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<% if @user.deleted_at == "退会済み" %>
	退会済みのユーザーです
<% else %>
	<% @user.errors.full_messages do |m| %>
	<%= m %>
	<% end %>

	<div class="users_show_mypage">
		<div class="users_show_left">
			<h1>プロフィール</h1>
			<div class="users_show_account">

				<div>
					<%= attachment_image_tag @user, :image, format: 'jpeg' ,fallback: 'no_image.jpg', class: "users_show_image_cicle" %>
				</div>
				<div class="users_show_name">
					<h1><%= @user.name %></h1>
				</div>
				<div class="users_show_profile_comment">
					<p><%= @user.profile %></p>
				</div>
				<% if @user == current_user %>
					<div>
							<% @buys.each do |buy| %>

								<% if buy.buy_products.where(delivery_status: "配送準備中").exists? %>
									<h5>発送が完了していない商品があります！</h5>
									<% break %>
								<% end %>
							<% end %>
						<h2>
							<%= link_to '商品発送状況', "/delivery" %>
						</h2>
					</div>
					<div>
						<h2><%= link_to "購入履歴", buy_path(@user.id)%></h2>

					</div>
					<div>
						<h2><%= link_to "編集", edit_user_path(@user.id),class: "fas fa-user-edit" %></h2>
					</div>
					<div>
						<h3><%= link_to "退会", user_path(@user.id), method: :delete, "data-confirm" => "本当に退会しますか？" %></h3>
					</div>
				<% end %>

			</div>
		</div>
		<div class="users_show_center">
			<h1>出品中商品</h1>
			<div class="users_show_products">
				<% @user.products.each do |product|%>
				<div class="users_show_shows">
					<%= link_to product_path(product.id),class: "users_show_shows_link" do %>


					<%= attachment_image_tag product, :image ,:size => "210x210", fallback: 'no_image.jpg', class: "users_show_image" %>


						　　　　　　　　　　　　　　　　　<!-- ---ボヤけて他ので400,400にしました--- -->
					<% end %>
					<table class="users_show_box bordercolor="#E6E6E6" rules="all"">
						<th>アーティスト名</td>
						<td><%= product.artist %></td>
					</tr>
					<tr>
						<th>CD/ALBUM名</td>
						<td><%= product.album %></td>
					</tr>
					<tr>
						<th>在庫数</td>
						<td><%= product.count %>枚</td>
					</tr>
					<tr>
						<th>値段</td>
						<td><%= product.price %>円/枚</td>
					</table>
					<% if @user == current_user %>
					<span><%= link_to "編集", edit_product_path(product.id)%></span>
					<span><%= link_to "削除", product_path(product.id), method: :delete,"data-confirm" => "本当に削除しますか?"  %></span>
					<% end %>
				</div>
				<hr>
				<% end %>
			</div>
		</div>
		<div class="users_show_right">
			<div class="users_show_chats_box">
			<h1>MELCD Chat</h1>
			<div class="users_show_chats">
				<div class="users_show_chats_table">
						<% @talk1.each do |talk| %>
						<div class="user_show_talks">

							<div class="user_show_talk_image", width="150px"><%= attachment_image_tag talk.user, :image,:size => "40x40",fallback: 'no_image.jpg', class: "users_show_chat_image_cicle" %></div>
 							<div class="product_show_comment_date">
                                <h6><%= talk.created_at.strftime('%Y/%m/%d') %></h6>
                            </div>
							<div class="user_show_talk_name" width="150px"><h5><%= talk.user.name  %></h5></div>
							<div class="product_show_balloon">
							<div class="user_show_talk_content"><%= talk.content %>
							<% if talk.user_id == current_user.id %>
								<div class="user_show_talk_destroy">
									<p><%= link_to "", talk_path(talk.id), method: :delete, class: "far fa-trash-alt my-gray", "data-confirm" => "本当に削除しますか?"%></p></div>
							</div>
							<% end %>
							</div>

						</div>
						<% end %>
				</div>
				<div class="users_show_chats_send">
					<%= form_for(@talk,url: talks_path(user_id: @user.id)) do |f| %>
					<%= f.text_area :content, :size => "50x10",placeholder:"文字以内" %>
                    <%= button_tag :type => "submit", :class =>" cart_btn" do %>
                      コメントする
                    <% end %>
					<% end %>
				</div>
			</div>
		</div>
		</div>
	</div>
<% end %>