config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :products
  resources :product_comments, only: [:create, :edit, :destroy]
  resources :carts, only: [:show, :index, :create]
  resources :cart_products, only: [:create, :update, :destroy]
  resources :talks, only: [:create, :destroy]
  resources :users, only: [:show, :edit, :destroy, :update]
  resources :buys, only: [:show]
  resources :buy_products, only: [:update, :destroy]
  resources :mails, only: [:create, :new]

  resources :admins, only: [:index, :show]
  get 'search' => 'searches#search', as: "search"
  get "/homes/about" => "homes#about"
  get '/delivery' => 'users#delivery'
  post '/delivery/:id' => 'users#delivery_create'
  root to: 'products#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
      # if user.admin?
      #   can :manage, :all
      # else
      #   can :read, :all
      # end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    if user && user.admin?
        can :access, :rails_admin
        can :manage, :all
    end
  end
end

app/models/buy.rb
class Buy < ApplicationRecord
	belongs_to :user
	has_many :buy_products, :dependent => :destroy
	belongs_to :delivery, inverse_of: :buys, optional: true
	enum payment: {クレジットカード: 0, 代金引換: 1, コンビニ払い: 2, 銀行振込: 3}
end

app/models/buy_product.rb
class BuyProduct < ApplicationRecord
	belongs_to :product
	belongs_to :buy
	enum delivery_status: {配送準備中: 0, 配送中: 1, 出荷済み: 2}
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_many :cart_products, :dependent => :destroy
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
	belongs_to :product
	belongs_to :cart

	validates :count,{presence: true}

end

app/models/delivery.rb
class Delivery < ApplicationRecord
	belongs_to :user
	has_many :buys, inverse_of: :delivery
	accepts_nested_attributes_for :buys
end

app/models/disc.rb
class Disc < ApplicationRecord
	belongs_to :product
	has_many :songs, inverse_of: :disc, :dependent => :destroy
	accepts_nested_attributes_for :songs, allow_destroy: true
end

app/models/mail.rb
class Mail < ApplicationRecord
	validates :name, :email, :subject, :content, presence: true
	belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord

	 enum genre: { 'J-POP': 0, 洋楽: 1, 'K-POP': 2, アニメ: 3, 'HIP-HOP': 4, レゲエ: 5,
	 	ロック: 6, 演歌: 7, エレクトロニック: 8, クラシック: 9, メタル: 10}
	 # enum genre: {aaa: 0, abb: 1, ccc: 3}
	 enum status: {新品: 0, 未使用に近い: 1, 目立った傷汚れなし: 2, 傷汚れあり: 3, 状態が悪い: 4}
	 enum delivery_status: {配送準備中: 0, 配送中: 1, 出荷済み: 2}


	 validates :artist, presence:true

	 validates :album, {presence:true}
	 validates :label, {presence:true}
	 validates :genre, {presence:true}
	 validates :status, {presence:true}
	 validates :introduction, {presence:true}
	 # validates :count, {presence:true}
	 validates :count,  presence: true
	 # validates :price, {presence:true}
	 validates :price,  presence: true

	belongs_to :user
	has_many :product_comments, :dependent => :destroy

 	has_many :discs, inverse_of: :product, :dependent => :destroy
	accepts_nested_attributes_for :discs, allow_destroy: true

	has_many :cart_products, :dependent => :destroy
	has_many :buy_products, :dependent => :destroy
	attachment :image
end

app/models/product_comment.rb
class ProductComment < ApplicationRecord
	belongs_to :user
	belongs_to :product

	validates :content, {presence:true}
end

app/models/room.rb
class Room < ApplicationRecord
	belongs_to :user
	has_many :talks, :dependent => :destroy
end

app/models/song.rb
class Song < ApplicationRecord
	belongs_to :disc
end

app/models/talk.rb
class Talk < ApplicationRecord
	belongs_to :room
	belongs_to :user

	validates :content,{presence: true}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum deleted_at: {登録中: 0, 退会済み: 1}

  def active_for_authentication?
    super && self.deleted_at == "登録中"
  end

  def inactive_message
    self.deleted_at == "登録中" ? super: :退会済みのユーザーです
  end

   has_many :mails
   has_many :products
   has_one :room
   has_many :talks
   has_many :product_comments
   has_one :cart
   has_many :deliveries
   has_many :buys

   attachment :image
   validates :name,:name_kana, :email, :password,:password_confirmation,:postal,:state,:street,:adress,:tel,{presence: true}


   validates :tel, length:{minimum:10}
   validates :tel, length:{maximum:11}
   validates :postal, length:{is:7}
   validates :password,length:{minimum:6}
   

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

	before_action :authenticate_user! ,only: [:show]
  before_action :cart_create, only: [:index]

  def cart_create
    if @cart = Cart.where(user_id: current_user.id).exists?
    else
      @cart = Cart.new(user_id: current_user.id)
      @cart.save
    end
  end

  def index
    @cart = Cart.find_by(user_id: current_user)
    @cart_products = CartProduct.where(cart_id: @cart.id)
    @cart_product = CartProduct.new

    @total_price = 0
    @total_count = 0
    @cart_products.each do |cartproduct|
    @total_price += cartproduct.product.price * cartproduct.count #---合計金額---#
    @total_count += cartproduct.count #---合計個数---#
    end
  end

  def create
    @cart = Cart.find(params[:cart_id])

    @current_cart_products = @cart.cart_products

    @current_cart_products.each do |current_cart_product|
      name = current_cart_product.id.to_s + "_count"
      current_cart_product.count = params[name]
      current_cart_product.save
    end

    redirect_to cart_path(@cart.id)

  end

  def show
    @cart = Cart.find_by(user_id: current_user)
    @cartproducts = CartProduct.where(cart_id: @cart.id)

    @buyproduct = BuyProduct.new
    @delivery = Delivery.new
    @delivery.buys.new

    @total_price = 0
    @cartproducts.each do |cartproduct|
      @total_price += cartproduct.product.price * cartproduct.count #---合計金額---#
    end
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/buys_helper.rb
module BuysHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/mails_helper.rb
module MailsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/index.html.erb
<div class="cart_index_cd">
	<% @cart_products.each do |cart_product| %>
	<div class="cart_index_cd_all clearfix">
		<div class="cart_index_cd_img clearfix">
			<%=link_to product_path(cart_product.product.id) do %>

        	<%= attachment_image_tag cart_product.product, :image, :size => "300x300",fallback: 'no_image.jpg'%>

        	<% end %>
        </div>
        <table rules="all" class="cart_index_cd_detail">
			<tr>
				<th>アーティスト</th>
				<td>
					<%=link_to cart_product.product.artist, product_path(cart_product.product.id) %>
				</td>
				</tr>
			<tr>

				<th>CD名</th>
				<td>
					<%=link_to cart_product.product.album, product_path(cart_product.product.id) %>
				</td>
			</tr>
			<tr>
				<th>注文数</th>
				<td>
					<%=cart_product.count %>
				</td>
			</tr>
			<tr>
				<th>出品者</th>
				<td>
					<%=cart_product.product.user.name %>
				</td>
			</tr>
		</table>
		<div>
			<table class="cart_index_cd_price">
				<tr>
					<th>単価</th><!-- あとでlinktoにさしかえ -->
					<td>
	                	¥<%= cart_product.product.price %>
	            	</td>
				</tr>
				<tr>
					<th>数量</th>
					<td></td><!-- あとでlinktoにさしかえ -->
				</tr>
			</table><br>
			<table class="cart_index_cd_price_small">
				<tr>
					<th>小計</td>
					<td>¥<%= cart_product.product.price * cart_product.count %></td><!-- あとでlinktoにさしかえ -->
				</tr>
			</table>
		</div>
			<div>
				<%= link_to'カートから削除', cart_product_path(cart_product.id), method: :delete %>
			</div>
	</div>

	<hr>
	<% end %>
</div>
	<div class="cart_index_cd_price_total_all">
		<table class="cart_index_cd_price_total">
			<tr>
				<th>合計点数</th>
				<th><h2><%= @total_count %>枚</h2></th>
				<th>合計金額</th>
				<th><h2>¥<%= @total_price %></h2></th>
				<th>
				<%= link_to(cart_path(@cart), class: 'cart_btn',:style =>"text-decoration:none")  do %>
  				<i class="fas fa-money-bill-alt"></i>レジに進む
				<% end %>
				</th>
			</tr>
		</table>
	</div>

app/views/carts/show.html.erb
<!-- カートのshowの箱（支払方法等を選択する） -->
<div class="carts_show_carts">


	<div class="carts_show_left">
		<h2>購入画面</h2>

		<% @cartproducts.each do |cartproduct| %>
		<div class="carts_show_buys">
			<div class="carts_show_buys_image">
				<%= attachment_image_tag cartproduct.product, :image, :fill, 400, 400, format: 'jpeg' ,fallback: 'no_image.jpg', class: "carts_show_buys_image" %>
				<!-- ---ボヤけて他ので100,100にしました--- -->
			</div>
			<table border= "1", class="carts_show_buys_box">
				<tr>
					<td class="cart_show_product_table">アーティスト名</td>
					<td class="cart_show_product_table"><%= cartproduct.product.artist %></td>
				</tr>
				<tr>
					<td class="cart_show_product_table">CD名</td>
					<td class="cart_show_product_table"><%= cartproduct.product.album %></td>
				</tr>
				<tr>
					<td class="cart_show_product_table">注文数</td>
					<td class="cart_show_product_table"><%= cartproduct.count %></td>
					<!-- 出品数の数になっていたので変更 -->
				</tr>
				<tr>
					<td class="cart_show_product_table">値段</td>
					<td class="cart_show_product_table"><%= cartproduct.product.price %></td>
				</tr>
			</table>
		</div>
		<% end %>
	</div>




	<!-- 支払い方法、送付先、合計金額、購入ボするボタンの箱 -->
	<div class="carts_show_right_box">
		<%= form_for(@delivery, url: buy_product_path(@cart.id), html: {method: "patch"}) do |f| %>

			<!-- 支払い方法、送付先、合計金額のテーブル -->
			<table class="cart_show_right_box_table">
				<!-- テーブルの1行目 -->
				<tr class="cart_show_right_box_tr">
					<!-- テーブルの左側の列 -->
					<td class="cart_show_right_box_td">支払方法
					</td>
					<!-- テーブル　：　の列 -->
					<td class="cart_show_right_box_td2">：
					</td>
					<!-- テーブル右側の列 -->
					<td class="cart_show_right_box_td3">
						<%= f.fields_for :buys do |buy|%>
							<%= buy.label :payment, "支払方法" %><br>
							<%= buy.select :payment, Buy.payments.keys.to_a, {} %>
							<%= buy.hidden_field :user_id, value: current_user.id %>
						<% end %>
					</td>
				</tr>

				<tr class="cart_show_right_box_tr">
					<!-- テーブルの左側の列 -->
					<td class="cart_show_right_box_td_child2">送付先
					</td>
					<td class="cart_show_right_box_td2_child2">：
					</td>
					<td class="cart_show_right_box_td3_child2">
						<%= f.label :name, "送付先氏名" %><br>
						<%= f.text_field :name,class: "cart_show_right_textfield" %><br>

						<%= f.label :postal, "郵便番号" %><br>
						<%= f.text_field :postal,class: "cart_show_right_textfield" %><br>

						<%= f.label :state, "都道府県" %><br>
						<%= f.text_field :state,class: "cart_show_right_textfield" %><br>

						<%= f.label :street, "市区町村" %><br>
						<%= f.text_field :street,class: "cart_show_right_textfield" %><br>

						<%= f.label :adress, "番地" %><br>
						<%= f.text_field :address,class: "cart_show_right_textfield" %><br>

						<%= f.label :tel, "電話番号" %><br>
						<%= f.text_field :tel,class: "cart_show_right_textfield" %>
					</td>
				</tr>

				<tr class="cart_show_right_box_tr">
					<!-- テーブルの左側の列 -->
					<td class="cart_show_right_box_td total_price">合計
					</td>
					<td class="cart_show_right_box_td2 total_price">：
					</td>
					<td class="cart_show_right_box_td3 total_price">¥<%= @total_price %>
					</td>
				</tr>
			</table>
			<!-- 支払い方法、送付先、合計金額のテーブルfin -->

			<!-- 購入ボタンの箱 -->
			<div class="cart_show_right_box_btn_box">
				<%= button_tag :type => "submit", :class =>"btn btn-default btn-s-md cart_btn" do %>
                          <i class="fas fa-truck fa-fw fa-4x"></i><strong>　購入を決定する</strong>
			</div>
			<% end %>
		<% end %>
	</div>
	<!-- 支払い方法、送付先、合計金額の箱fin -->


</div>
<!-- カートのshowの箱（支払方法等を選択する）fin -->