config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :products
  resources :product_comments, only: [:create, :edit, :destroy]
  resources :carts, only: [:show, :index, :create]
  resources :cart_products, only: [:create, :update, :destroy]
  resources :talks, only: [:create, :destroy]
  resources :users, only: [:show, :edit, :destroy, :update]
  resources :buys, only: [:show]
  resources :buy_products, only: [:update, :destroy]
  resources :mails, only: [:create, :new]

  resources :admins, only: [:index, :show]
  get 'search' => 'searches#search', as: "search"
  get "/homes/about" => "homes#about"
  get '/delivery' => 'users#delivery'
  post '/delivery/:id' => 'users#delivery_create'
  root to: 'products#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
      # if user.admin?
      #   can :manage, :all
      # else
      #   can :read, :all
      # end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    if user && user.admin?
        can :access, :rails_admin
        can :manage, :all
    end
  end
end

app/models/buy.rb
class Buy < ApplicationRecord
	belongs_to :user
	has_many :buy_products, :dependent => :destroy
	belongs_to :delivery, inverse_of: :buys, optional: true
	enum payment: {クレジットカード: 0, 代金引換: 1, コンビニ払い: 2, 銀行振込: 3}
end

app/models/buy_product.rb
class BuyProduct < ApplicationRecord
	belongs_to :product
	belongs_to :buy
	enum delivery_status: {配送準備中: 0, 配送中: 1, 出荷済み: 2}
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_many :cart_products, :dependent => :destroy
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
	belongs_to :product
	belongs_to :cart

	validates :count,{presence: true}

end

app/models/delivery.rb
class Delivery < ApplicationRecord
	belongs_to :user
	has_many :buys, inverse_of: :delivery
	accepts_nested_attributes_for :buys
end

app/models/disc.rb
class Disc < ApplicationRecord
	belongs_to :product
	has_many :songs, inverse_of: :disc, :dependent => :destroy
	accepts_nested_attributes_for :songs, allow_destroy: true
end

app/models/mail.rb
class Mail < ApplicationRecord
	validates :name, :email, :subject, :content, presence: true
	belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord

	 enum genre: { 'J-POP': 0, 洋楽: 1, 'K-POP': 2, アニメ: 3, 'HIP-HOP': 4, レゲエ: 5,
	 	ロック: 6, 演歌: 7, エレクトロニック: 8, クラシック: 9, メタル: 10}
	 # enum genre: {aaa: 0, abb: 1, ccc: 3}
	 enum status: {新品: 0, 未使用に近い: 1, 目立った傷汚れなし: 2, 傷汚れあり: 3, 状態が悪い: 4}
	 enum delivery_status: {配送準備中: 0, 配送中: 1, 出荷済み: 2}


	 validates :artist, presence:true

	 validates :album, {presence:true}
	 validates :label, {presence:true}
	 validates :genre, {presence:true}
	 validates :status, {presence:true}
	 validates :introduction, {presence:true}
	 # validates :count, {presence:true}
	 validates :count,  presence: true
	 # validates :price, {presence:true}
	 validates :price,  presence: true

	belongs_to :user
	has_many :product_comments, :dependent => :destroy

 	has_many :discs, inverse_of: :product, :dependent => :destroy
	accepts_nested_attributes_for :discs, allow_destroy: true

	has_many :cart_products, :dependent => :destroy
	has_many :buy_products, :dependent => :destroy
	attachment :image
end

app/models/product_comment.rb
class ProductComment < ApplicationRecord
	belongs_to :user
	belongs_to :product

	validates :content, {presence:true}
end

app/models/room.rb
class Room < ApplicationRecord
	belongs_to :user
	has_many :talks, :dependent => :destroy
end

app/models/song.rb
class Song < ApplicationRecord
	belongs_to :disc
end

app/models/talk.rb
class Talk < ApplicationRecord
	belongs_to :room
	belongs_to :user

	validates :content,{presence: true}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum deleted_at: {登録中: 0, 退会済み: 1}

  def active_for_authentication?
    super && self.deleted_at == "登録中"
  end

  def inactive_message
    self.deleted_at == "登録中" ? super: :退会済みのユーザーです
  end

   has_many :mails
   has_many :products
   has_one :room
   has_many :talks
   has_many :product_comments
   has_one :cart
   has_many :deliveries
   has_many :buys

   attachment :image
   validates :name,:name_kana, :email, :password,:password_confirmation,:postal,:state,:street,:adress,:tel,{presence: true}


   validates :tel, length:{minimum:10}
   validates :tel, length:{maximum:11}
   validates :postal, length:{is:7}
   validates :password,length:{minimum:6}
   

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController


  def index
    @products = Product.all.order(created_at: "DESC")
    @users = User.all
    @user = current_user
    @jpops2 = Product.where(genre: 'J-POP')
    @jpops = @jpops2.order(created_at: "DESC")
    @kpops2 = Product.where(genre: 'K-POP',)
    @kpops = @kpops2.order(created_at: "DESC")
    @worlds2 = Product.where(genre: '洋楽')
    @worlds = @worlds2.order(created_at: "DESC")
  end

  def show
    @product = Product.find(params[:id])
    @product_comment = ProductComment.new
    @cart_product = CartProduct.new

    # 在庫数をインスタンス変数に入れて、viewのselectフォームに渡します。
    @count_array = []
    @product.count.times do |quantitiy|
      if quantitiy < @product.count
        @count_array << [quantitiy+1,quantitiy+1]
      else
        break
      end
    end
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    if @product.save
      redirect_to products_path
    else
      @product.errors.full_messages
      render "products/new"
    end

  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to product_path(@product.id)
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:artist,:album,:title,:image,:label,:genre,:status,:introduction,:count,:price,:new_price,discs_attributes: [:id, :number, :_destroy,songs_attributes: [:id, :title, :_destroy]])
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/buys_helper.rb
module BuysHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/mails_helper.rb
module MailsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_disc_fields.html.erb
<div class="nested-fields disc_cocoon_form">
	<div class="disc_fields_remove_disc_btn_position">
		<%= link_to_remove_association "ディスクを削除", f, class: "disc_fields_remove_disc_btn" %>
	</div>
	<div>
		<%= f.fields_for :songs do |song| %>
			<%= render 'song_fields', f: song %>
		<% end %>

		<div class="desic_fields_add_songs_btn_psition">
			<%= link_to_add_association "曲名を追加", f, :songs, data: {association_insertion_method: 'append'}, class: "disc_fields_add_songs_btn" %>
		</div>
	</div>
</div>

app/views/products/_form.html.erb
<!-- いらない記述 -->
<%= form_for @product do |f| %>


<% end %>

app/views/products/_song_fields.html.erb
<div class="nested-fields">
	<div class="song_fields_form">
		・<%= f.text_field :title %>
	</div>

	<div class="song_fields_remove_song_btn_position">
		<%= link_to_remove_association "上の曲を削除", f, class:"song_fields_remove_song_btn" %>
	</div>

</div>

app/views/products/edit.html.erb
<div class="product_edit_box">
    <div class="product_edit_middle">
        <div class="product_edit_etc">
            <div class="product_edit_small">
            <%= form_for(@product) do |f|%>
                <div class="product_edit_album">
                    <h2>CD名<%= f.text_field :album, class: "product_edit_album_name"  %></h2>
                </div>
                <div class="product_edit_image">
                    <%= attachment_image_tag @product, :image ,:size => "300x300",fallback: "no_image.jpg",class: "product_edit_image_border" %>
                </div>
                <div class="product_edit_table2">
                        <table class="product_edit_table3 bordercolor="#E6E6E6" rules="all" >
                            <caption></caption>
                            <thead>
                                <tr>
                                    <td class="product_edit_table4">出品者</td><td><%= link_to user_path(@product.user.id),:style =>"text-decoration:none;" do |f| %>
                                        <%= @product.user.name%></td>
                                        <% end %>
                                </tr>
                                <tr>
                                    <td class="product_edit_table4">在庫数</td><td><%=f.number_field :count, class: "product_edit_number" %>個</td>
                                </tr>
                                <tr>
                                    <td class="product_edit_table4">レーベル</td><td><%= f.text_area :label %></td>
                                </tr>
                                <tr>
                                    <td class="product_edit_table4">ジャンル </td><td><%= f.select :genre,Product.genres.keys.to_a, {} %></td>
                                </tr>
                                <tr>
                                    <td class="product_edit_table4">状態</td><td><%= f.select :status,Product.statuses.keys.to_a, {} %></td>
                                </tr>
                            </thead>
                        </table>
                </div>
            </div>
            <div class="product_edit_song">
                <h1>曲目</h1>
                    <div class="product_edit_add_disc_btn_position">
                        <%= link_to_add_association 'さらにディスクを追加', f, :discs, data: {association_insertion_method: 'append'}, class:"product_add_disc_btn" %>
                    </div>
                    <div>
                    <%= f.fields_for :discs do |disc| %>
                        <%= render 'disc_fields', f: disc %>
                    <% end %>
                    </div>

            </div>
            <div class="product_edit_price">
                <% if @product.new_price == nil %>
                    ¥<%= f.number_field :price, class: "product_edit_price_edit" %>
                <% else %>
                    ¥<%= f.number_field :new_price  %>
                <% end %>
            </div>
            <div class="product_edit_introduction">
                <%= f.text_area :introduction ,:size =>"47x30", class: "product_edit_introduction_text" %>
            </div>
            <%= button_tag :type => "submit", :class =>" cart_btn" do %>
                      変更を保存
        <% end %>
        <% end %>
        </div>
    </div>

</div>

app/views/products/new.html.erb
<% @product.errors.full_messages.each do |message| %>
	<%= message %>
<% end %>

<div class="product_new_big_box">

<div class="product_new_middle_box">
<%= form_for(@product) do |f| %>
	<h1>アーティスト名</h1>
	<%= f.text_field :artist %>
	<h1>CD/ALBUM名</h1>
	<%= f.text_field :album %>
   	<h1>画像</h1>
  	<%= f.attachment_field :image %>
    <h1>レーベル</h1>
	<%= f.text_field :label %>
	<h2>ジャンル</h2>

	<%= f.select :genre, Product.genres.keys.to_a, {} %><br>

	<h2>状態</h2>
	<%= f.select :status,Product.statuses.keys.to_a, {} %>

	<h2>ディスク</h2>


	<div class="product_add_disc_btn_position">
			<%= link_to_add_association 'ディスクを追加', f, :discs, data: {association_insertion_method: 'append'}, class: "product_add_disc_btn" %>
	</div>
	<div>
		<!-- f.fields_forは、cocoonをインストールすると使用できる？っぽいです -->
		<!-- ほぼform_forと機能は同じです。 -->
		<!-- 異なるのは、①上述の通りネストしたモデルの内容をparams回収ができる点、②下記のlink_to_add_associationのリンクが押されると表示できる点 -->
		<%= f.fields_for :discs do |disc| %>
			<!-- renderで部分テンプレートdiscs_fields.html.erbを呼び出している。上記②の通り下記のlink_to_add_associationを押すことで呼び出す。 -->
			<%= render 'disc_fields', f: disc %>
		<% end %>
	</div>

	<h1> CDの説明</h1>
	<%= f.text_area :introduction, cols:70, rows:10 %>
	<h1>数量</h1>
	<%= f.number_field :count,size:5 %><span>枚</span><br>
	<h1>値段</h1>
	<%= f.number_field :price %><span>円/枚</span><br>

	<%= f.submit '出品する' ,:class=>"product_new_btn" %>
	<% end %>
 </div>

app/views/products/show.html.erb
<% @cart_product.errors.full_messages.each do |message| %>
 <%= message %>
<% end %>

<% if flash[:notice] %>
	<div class="products_show_flash">
		<%= flash[:notice] %>
	</div>
<% end %>



<div class="product_show_box">
        <!-- 草野デザイン修正 -->
    <div class="product_show_middle">
        <div class="product_show_etc">
            <div class="product_show_small">

            <div class="product_show_album">

                <h1><%= @product.album %>/<%= @product.artist %></h1>

            </div>
            <div class="product_show_image">
                <%= attachment_image_tag @product, :image ,:size => "300x300",fallback: 'no_image.jpg' %>
            </div>
            <div class="product_show_table2">
                    <table class="product_show_table3 bordercolor="#E6E6E6" rules="all" >
                        <caption></caption>
                        <thead>
                             </thead>
                            <tr>
                                <td class="product_show_table4">出品者</td><td><%= link_to user_path(@product.user.id),:style =>"text-decoration:none" do |f| %>
                                    <%= @product.user.name%></td>
                                    <% end %>
                            </tr>
                             </tr>
                            	<td class="product_show_table4">アーティスト名</td><td><%= @product.artist %></td>
                            </tr>
                            <tr>
                                <td class="product_show_table4">在庫数</td><td><%= @product.count %>個</td>
                            </tr>
                            <tr>
                                <td class="product_show_table4">レーベル</td><td><%= @product.label %></td>
                            </tr>
                            <tr>
                                <td class="product_show_table4">ジャンル </td><td><%= @product.genre_i18n %></td>
                            </tr>
                            <tr>

                                <td class="product_show_table4">状態</td><td><%= @product.status %></td>
                            </tr>

                        <tbody>
                        </tbody>
                    </table>
                    <div class="product_show_gocart">
 <!--                        <% if @product.user.id != current_user.id %>
                        <%=form_for(@cart_product, url:cart_product_path(@product.id), html:{method: :patch}) do |f| %>
                        <%=f.number_field :count, :size => "10x8",placeholder:"個数"%><br>
                        <%= button_tag :type => "submit", :class =>"btn btn-default btn-s-md cart_btn" do %>
                          <i class="fas fa-cart-plus fa-fw fa-2x"></i>カートへ
                        <% end %>
                        <% else %>
                        <% end %>
                        <% end %> -->

                        <div>
                            <% if current_user != nil %>
                            <% if @product.user.id == current_user.id %>
                            <h5><%= link_to "編集する", edit_product_path(@product.id),:style=>"color: #222222; text-decoration:none "%>
                            <%= link_to "削除する", product_path(@product.id),:style=>"color: #222222; text-decoration:none ", method: :delete, "data-confirm" => "本当に削除しますか？"%></h5>
                            <% else %>
                            <% end %>
                            <% else %>
                            <% end %>
                        </div>
                    </div>
            </div>
        </div>
        <div class="product_show_song">
            <h1>曲目</h1>
                <% @product.discs.each do |disc| %>
                    <% disc.songs.each do |song| %>
                        ・<%= song.title %><br>
                    <% end %>
                <% end %>
        </div>
        <div class="product_show_price">
            <% if @product.new_price == nil %>
                ¥<%= @product.price %>
            <% else %>
                ¥<%= @product.new_price %>
            <% end %>
        </div>
        <div class="product_show_introduction">
            ・<%= @product.introduction %>
        </div>
        <div class="product_show_chat">
            <div class="product_show_table">
                <table class="product_show_table">
                    <div class="product_show_chatt">
                            <% @product.product_comments.each do |product_comment| %>

                        <div class="product_show_comments">
                            <div class="product_show_comment_image", width="150px"><%= attachment_image_tag product_comment.user, :image, :fill, 100, 100,fallback: 'no_image.jpg', class: "users_show_image_cicle" %>
                            </div>
                            <div class="product_show_comment_date">
                                <h5><%= product_comment.created_at.strftime('%Y/%m/%d') %></h5>
                            </div>
                            <div class="product_show_comment_name" width="150px">
                                <h5><%= product_comment.user.name  %></h5>
                            </div>
                            <div class="product_show_balloon">
                                <div class="product_show_comment_content" width="200px">
                                    <%= product_comment.content %>
                                    <% if product_comment.user_id == current_user.id %>
                                    <div class="product_show_comment_destroy">
                                        <p>
                                        <%= link_to "", product_comment_path(product_comment.id), method: :delete, class: "far fa-trash-alt my-gray", "data-confirm" => "本当に削除しますか?"%>
                                        </p>
                                     </div>
                                </div>
                            </div>

                            <% end %>
                        </div>
                     <% end %>
                    </div>
                </table>
            </div>
        </div>
                    <%= form_for(@product_comment,url: product_comments_path(product_id: @product.id)) do |f| %>

                    <%= f.text_area :content ,:size => "150x8" ,placeholder:"200文字以内"%><br>

                    <%= f.submit "コメントする" ,:class=>"bottan" %>
                    <% end %>
                <div class="product_show_gocart">
                    <% if @product.user.id != current_user.id %>
                    <%=form_for(@cart_product, url:cart_product_path(@product.id), html:{method: :patch}) do |f| %>
                    <%=f.select :count, @count_array, :size => "10x8",placeholder:"個数"%>
                    <%=f.submit "カートに入れる" %>
                     <% else %>
                    <% end %>
                    <% end %>
        </div>
    </div>
</div>