config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :products
  resources :product_comments, only: [:create, :edit, :destroy]
  resources :carts, only: [:show, :index, :create]
  resources :cart_products, only: [:create, :update, :destroy]
  resources :talks, only: [:create, :destroy]
  resources :users, only: [:show, :edit, :destroy, :update]
  resources :buys, only: [:show]
  resources :buy_products, only: [:update, :destroy]
  resources :mails, only: [:create, :new]

  resources :admins, only: [:index, :show]
  get 'search' => 'searches#search', as: "search"
  get "/homes/about" => "homes#about"
  get '/delivery' => 'users#delivery'
  post '/delivery/:id' => 'users#delivery_create'
  root to: 'products#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
      # if user.admin?
      #   can :manage, :all
      # else
      #   can :read, :all
      # end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    if user && user.admin?
        can :access, :rails_admin
        can :manage, :all
    end
  end
end

app/models/buy.rb
class Buy < ApplicationRecord
	belongs_to :user
	has_many :buy_products, :dependent => :destroy
	belongs_to :delivery, inverse_of: :buys, optional: true
	enum payment: {クレジットカード: 0, 代金引換: 1, コンビニ払い: 2, 銀行振込: 3}
end

app/models/buy_product.rb
class BuyProduct < ApplicationRecord
	belongs_to :product
	belongs_to :buy
	enum delivery_status: {配送準備中: 0, 配送中: 1, 出荷済み: 2}
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_many :cart_products, :dependent => :destroy
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
	belongs_to :product
	belongs_to :cart

	validates :count,{presence: true}

end

app/models/delivery.rb
class Delivery < ApplicationRecord
	belongs_to :user
	has_many :buys, inverse_of: :delivery
	accepts_nested_attributes_for :buys
end

app/models/disc.rb
class Disc < ApplicationRecord
	belongs_to :product
	has_many :songs, inverse_of: :disc, :dependent => :destroy
	accepts_nested_attributes_for :songs, allow_destroy: true
end

app/models/mail.rb
class Mail < ApplicationRecord
	validates :name, :email, :subject, :content, presence: true
	belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord

	 enum genre: { 'J-POP': 0, 洋楽: 1, 'K-POP': 2, アニメ: 3, 'HIP-HOP': 4, レゲエ: 5,
	 	ロック: 6, 演歌: 7, エレクトロニック: 8, クラシック: 9, メタル: 10}
	 # enum genre: {aaa: 0, abb: 1, ccc: 3}
	 enum status: {新品: 0, 未使用に近い: 1, 目立った傷汚れなし: 2, 傷汚れあり: 3, 状態が悪い: 4}
	 enum delivery_status: {配送準備中: 0, 配送中: 1, 出荷済み: 2}


	 validates :artist, presence:true

	 validates :album, {presence:true}
	 validates :label, {presence:true}
	 validates :genre, {presence:true}
	 validates :status, {presence:true}
	 validates :introduction, {presence:true}
	 # validates :count, {presence:true}
	 validates :count,  presence: true
	 # validates :price, {presence:true}
	 validates :price,  presence: true

	belongs_to :user
	has_many :product_comments, :dependent => :destroy

 	has_many :discs, inverse_of: :product, :dependent => :destroy
	accepts_nested_attributes_for :discs, allow_destroy: true

	has_many :cart_products, :dependent => :destroy
	has_many :buy_products, :dependent => :destroy
	attachment :image
end

app/models/room.rb
class Room < ApplicationRecord
	belongs_to :user
	has_many :talks, :dependent => :destroy
end

app/models/song.rb
class Song < ApplicationRecord
	belongs_to :disc
end

app/models/talk.rb
class Talk < ApplicationRecord
	belongs_to :room
	belongs_to :user

	validates :content,{presence: true}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum deleted_at: {登録中: 0, 退会済み: 1}

  def active_for_authentication?
    super && self.deleted_at == "登録中"
  end

  def inactive_message
    self.deleted_at == "登録中" ? super: :退会済みのユーザーです
  end

   has_many :mails
   has_many :products
   has_one :room
   has_many :talks
   has_many :product_comments
   has_one :cart
   has_many :deliveries
   has_many :buys

   attachment :image
   validates :name,:name_kana, :email, :password,:password_confirmation,:postal,:state,:street,:adress,:tel,{presence: true}


   validates :tel, length:{minimum:10}
   validates :tel, length:{maximum:11}
   validates :postal, length:{is:7}
   validates :password,length:{minimum:6}
   

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/buys_helper.rb
module BuysHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/mails_helper.rb
module MailsHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Merucd</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

<!-- ここからヘッダー -->
    <header>
      <nav class="products_index_header clearfix">
        <div class="products_index_header_title">
      <a href="/"><img src='/assets/logo2.png'class="products_index_header_logo"></a>
       </div>
            <!-- 検索機能-->
            <div class="products_index_search">
              <div class="products_index_search_box">
                <%= search_form_for @q, html: {class: 'products_index_column'}, url: search_path do |f|%>
                  <%= f.condition_fields do |c| %>
<!-- ここで検索するカラムを指定できる。しかし、カラムを任意のものに絞り込むのは無理そう -->
                    <%= c.attribute_fields do |a| %>
                      <%= a.attribute_select associations: [] %>
                    <% end %>
 <!-- ここで曖昧検索の仕方を指定している。これはc.hidden_field :p, value:を使って絞り込むことが可能 -->
                    <%= c.hidden_field :p, value: "cont" %>
                    <%= c.value_fields do |v| %>
                      <%= v.search_field :value, placeholder: '検索ワードを入力' %>
                    <% end %>
                  <% end %>
                  <%= f.submit '検索' %>
                <% end %>
              </div>

            <ul class="products_index_header_itembox">
            <!-- ここはログイン時のみ -->
          <% if user_signed_in? %>
            <li class="products_index_header_item">
              <%= link_to current_user.name, user_path(current_user.id), :style=>"color: #222222; text-decoration:none; font-size:14px "  %>
            </li>
            <li class="products_index_header_item">
              <%= link_to "カートへ", carts_path, :style=>"color: #222222; text-decoration:none; font-size:14px"  %>
            </li>
            <li class="products_index_header_item">
              <%= link_to "ログアウト", destroy_user_session_path, :style=>"color: #222222; text-decoration:none; font-size:14px", method: :delete  %>
            </li>
            <!-- ここ以下がログアウト時のみ -->
          <% else %>
            <li class="products_index_header_item">
              <%= link_to "新規登録", new_user_registration_path,:style=>"color: #222222; text-decoration:none; font-size:14px" %>
            </li>
            <li class="products_index_header_item">
              <%= link_to " ログイン", new_user_session_path,:style=>"color: #222222; text-decoration:none; font-size:14px" %>
          <% end %>
            </li>
        </ul>
        </div>
      </nav>
    </header>
    <%= yield %>
<!-- ここからフッター -->
    <footer>
      <nav class="products_index_footer">
        <ul class="products_index_footer_itembox">
            <li class="products_index_footer_item">
              <%= link_to "お問い合わせ", new_mail_path,:style=>"color:white; text-decoration:none;" %>
            </li>
            <li class="products_index_footer_item">
              <%= link_to "このサイトについて", homes_about_path,:style=>"color:white; text-decoration:none;" %>
            </li>
        </ul>
              <span class="products_index_footer_c">©︎ks-㎡</span>
      </nav>
    </footer>
  </body>
</html>